apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rider-function
  name: rider-function
spec:
  ports:
    - port: 5010
      protocol: TCP
      targetPort: 5010
  selector:
    app: rider-function
status:
  loadBalancer: {}
